### ISSUE TITLE
MQTT_MAX_PACKET_SIZE error when compiling / sending MQTT firmware

### ISSUE THREAD

**Issue by MagicFab** [mcer12/Hugh-ESP8266#17]
I am fairly new to Arduino.

I am using Debian 10 with Arduino IDE setup for ESP8255 module upload, I've added PubSubClient and EspMQTTClient libraires. I am trying to upload the latest MQTT firmware on a Hugo remote I recenly got.

I've connected the remote via USB, loaded the MQTT firmware files in Arduino IDE, when using "Verify/Compile", I get this error:
#error "MQTT_MAX_PACKET_SIZE is too small in libraries/PubSubClient/src/PubSubClient.h, increase it to 512"

Uploading the diyHUE firmware works fine on the same remote.

Am I missing a particular library or requirement ? Thanks in advance.

**Comment by mcer12** [comment]
Yes, the library packet size is too small by default and there's no other way to change it than in the library itself. You have to edit the library according to the error, that's why I put it there :D 
Hugo_MqttTrigger.ino, line 74

**Comment by MagicFab** [comment]
That worked, thank you!
