### ISSUE TITLE
Is this product available anymore

### ISSUE THREAD

**Issue by just-local-apps** [mcer12/Hugh-ESP8266#26]
First of all sorry to spam in GitHub issues, but I had no choice as tindie wouldn't send an email to activate my account to contact seller. 

I just ordered 3 from tindie, but it ran out of stock. I wanted to buy 2 more. Also, how would I replace the battery? Any link to buy similar battery

Thanks,
Ravi R

**Comment by mcer12** [comment]
I believe this was answered on Tindie ;)
