### ISSUE TITLE
configuration webpage doesn't show complete payload

### ISSUE THREAD

**Issue by just-local-apps** [mcer12/Hugh-ESP8266#29]
Issue:
I have set the value of "{"siteId": "hugo1"}" in the payload value. The setting is saved in Hugo. It sends the correct payload to Matt server. But it doesn't show up when I open the configuration page again. 

Actual:
![Screen Shot 2020-06-30 at 7 41 55 AM](https://user-images.githubusercontent.com/6249312/86122312-9fb48700-baa5-11ea-9a77-39eda533b1db.png)

Expected:
The complete string "{"siteId": "hugo1"}" should show up in the configuration page

**Comment by mcer12** [comment]
It only accepts simple text/number strings. It's stored in json file so the payload itself being json is not gonna work, or at least not correctly :) The main issue would probably be the quotes. You should do something like Topic: siteId, Payload: hugo1
