### ISSUE TITLE
HTTP (Basic URL trigger)

### ISSUE THREAD

**Issue by patrickdej** [mcer12/Hugh-ESP8266#32]
Hello,
we have inserted an URL into the Hugo, but the request is executed as a TCP message and not as an http request (seen in wireshark)
Whats wrong?

URL set to this http://172.20.20.153:8080/#/Main/Acknowledge?Sendkey=T1_S1_G
when executing this URL from an phone on the same network (just past it into the browser), it works fine.
so no issue on firewall.
172.20.20.122 is the phone, TCP connection OK, http OK
172.20.20.170 is the Hugo ==> TCP NOK and thus no http transfer possible
![image](https://user-images.githubusercontent.com/61730901/92883082-d34e4e80-f410-11ea-8dfc-b85075af6c4e.png)

thanks,

Patrick

**Comment by mcer12** [comment]
Hi, I think this might have something to do with the port in your URL address. I never tried/needed this so this is probably what's the issue here. Lets start by removing the port from the URL address (so it will be 80 by default), see if it works.

**Comment by patrickdej** [comment]
OK, works fine now. was due to the way the website worked, it needed more then only 1 url...
thanks!
