### ISSUE TITLE
Configure without ConfigPortal

### ISSUE THREAD

**Issue by coolnovember** [mcer12/Hugh-ESP8266#34]
Hello,
I have a few of your devices. 
Is there a way to program the configuration info without using the config portal? i.e. directly into the Sketch?
I saw some code to write to the SPIFFS, but that seems to need the portal do things.

As one idea, do you have some documentation on the format of the image that the Hugo saves to SPIFSS? 
I could build the file and upload it directly without using the portal?

**Comment by mcer12** [comment]
@coolnovember You can set default values in the sketch, fns.ino on line 188 are all values set to empty. You can just set them to differnt value there.

**Comment by coolnovember** [comment]
That worked! Thanks!
