### ISSUE TITLE
Possibly release gerber files now that product is retired?

### ISSUE THREAD

**Issue by nullstalgia** [mcer12/Hugh-ESP8266#36]
I forgot to grab one while the last batch went up, and I wanted to maybe yoink the design you had.

If not, that's fine! Just thought I should ask. <3

**Comment by mcer12** [comment]
I added the gerber, with all the usual disclaimers. But to be honest, at this point it makes more sense to use ESP32 as it has more GPIOs, much easier to work with deepsleep and it has half the power consumption in deep sleep. You can compensate for the ESP32 size with smaller component count. I personally switched over to ESP32 for most projects, except when I need it super tiny, where ESP-M2 makes more sense.
