### ISSUE TITLE
Battery reporting topics

### ISSUE THREAD

**Issue by giddyhup** [mcer12/Hugh-ESP8266#6]
Great soft- and hardware! Apparently, a Hugo reports its battery level under two topics, is this on purpose? Also, 0x3e is 62 not 90, what does it stand for? 

```
esp/hugh/battery 3e
esp/hugo/battery 90

```
I use two Hugos. It would make sense to have the status topics configurable through the web interface.

**Comment by mcer12** [comment]
Sorry for getting back to you so late, I didn't receive a notification... this is a bug and will be solved in the upcoming update. I'll comment here once its pushed in the git. Hopefully today.

**Comment by mcer12** [comment]
@giddyhup This should also be fixed with the latest sketch.

**Comment by giddyhup** [comment]
Thanks for the update. The line `publishBatteryLevel();` is missing in the code for button 1.

Also, the topic is not unique. I can't tell the battery reporting apart when I have two Hugos. Here's what I did:

````
void publishBatteryLevel() {
  client.publish(String("hugo" + macLastThreeSegments(mac) + "/battery").c_str(), String(batteryPercentage()).c_str()) ;
  Serial.print("Battery: ");
  Serial.println(batteryPercentage());
}

````

**Comment by mcer12** [comment]
Thanks, you're correct. I pushed your solution.
I will add an option for custom topic in the next update.

**Comment by giddyhup** [comment]
Good idea. In my case I named my two Hugos (red and black) and put the respective names in the topics.

**Comment by mcer12** [comment]
@giddyhup Check out the latest update, it's a bigger one.

**Comment by giddyhup** [comment]
Thanks. I will check it out when I return from my trip in a couple of weeks. Meanwhile, I'll close this issue.
