### ISSUE TITLE
MQTT client ID should unique/random

### ISSUE THREAD

**Issue by giddyhup** [mcer12/Hugh-ESP8266#7]
Duplicate MQTT client IDs are against specifications. Each device should have its own unique ID. When multiple Hugos are in use this may cause conflicts. Possible conflicts are mitigated since a Hugo is connected to the broker only for a short while but it would be better if the ID would be randomized (as it is done in other projects) and not hardcoded.

Edit:
PS.: ~I would also consider randomizing OTA names.~ In OTA names this seems to already be implemented.

**Comment by mcer12** [comment]
Last three segments (6 characters) of the MAC address will be appended in the device name. I will let you know once the update is ready.

**Comment by mcer12** [comment]
@giddyhup Try out latest sketch
